export const CATEGORIES = [
  { id: 'all', label: 'All', icon: '🏋️', color: '#94a3b8' },
  { id: 'chest', label: 'Chest', icon: '💪', color: '#ef4444' },
  { id: 'back', label: 'Back', icon: '🏃', color: '#f97316' },
  { id: 'legs', label: 'Legs', icon: '🦵', color: '#22c55e' },
  { id: 'shoulders', label: 'Shoulders', icon: '🤸', color: '#3b82f6' },
  { id: 'arms', label: 'Arms', icon: '💪', color: '#a855f7' },
  { id: 'core', label: 'Core', icon: '🔥', color: '#f59e0b' },
  { id: 'cardio', label: 'Cardio', icon: '⚡', color: '#06b6d4' },
];

// angleType options:
// 'elbow'    → shoulder-elbow-wrist  (push variations, rows, press, curls)
// 'knee'     → hip-knee-ankle        (squat, lunge, bridge)
// 'elbowCurl'→ elbow angle, invertRep (bicep curls — up=flexed/small angle)
// 'hip'      → shoulder-hip-knee     (good morning, back ext)
// 'trunk'    → vertical shoulder displacement (crunches)
// 'kneeRaise'→ hip-knee angle        (high knees, leg raise)

export const exercises = [
  // ── CHEST ──────────────────────────────────────────────
  {
    id: 'push-ups', name: 'Push-ups', category: 'chest', icon: '💪', level: 'Beginner',
    color: '#ef4444', gradient: 'linear-gradient(135deg,#ef4444,#f97316)',
    targetMuscles: 'Chest, Shoulders, Triceps',
    description: 'Classic compound exercise targeting pectorals.',
    keyPoints: ['Body in straight line', 'Hands shoulder-width', 'Lower chest to floor', 'Full arm extension'],
    angleType: 'elbow', downThreshold: 100, upThreshold: 155,
  },
  {
    id: 'wide-push-ups', name: 'Wide Push-ups', category: 'chest', icon: '🤲', level: 'Intermediate',
    color: '#f97316', gradient: 'linear-gradient(135deg,#f97316,#fbbf24)',
    targetMuscles: 'Outer Chest, Shoulders',
    description: 'Wide-grip push-up emphasising outer pectorals.',
    keyPoints: ['Hands 1.5× shoulder width', 'Elbows flare out', 'Lower chest to hands', 'Full extension'],
    angleType: 'elbow', downThreshold: 100, upThreshold: 155,
  },
  {
    id: 'diamond-push-ups', name: 'Diamond Push-ups', category: 'chest', icon: '💎', level: 'Intermediate',
    color: '#e879f9', gradient: 'linear-gradient(135deg,#e879f9,#a855f7)',
    targetMuscles: 'Inner Chest, Triceps',
    description: 'Close-grip diamond-hand push-up for triceps and inner chest.',
    keyPoints: ['Thumbs and index fingers touch', 'Elbows close to body', 'Full depth', 'Core tight'],
    angleType: 'elbow', downThreshold: 100, upThreshold: 155,
  },
  {
    id: 'pike-push-ups', name: 'Pike Push-ups', category: 'chest', icon: '🔺', level: 'Intermediate',
    color: '#14b8a6', gradient: 'linear-gradient(135deg,#14b8a6,#06b6d4)',
    targetMuscles: 'Shoulders, Upper Chest',
    description: 'Downward-dog push-up hitting shoulders and upper chest.',
    keyPoints: ['Hips high', 'Lower head to floor', 'Push back up fully', 'Elbows back not out'],
    angleType: 'elbow', downThreshold: 100, upThreshold: 155,
  },
  {
    id: 'decline-push-ups', name: 'Decline Push-ups', category: 'chest', icon: '📐', level: 'Intermediate',
    color: '#22d3ee', gradient: 'linear-gradient(135deg,#22d3ee,#3b82f6)',
    targetMuscles: 'Upper Chest, Front Deltoids',
    description: 'Feet-elevated push-up targeting upper chest.',
    keyPoints: ['Feet elevated', 'Straight body line', 'Lower chest to floor', 'Explosive press up'],
    angleType: 'elbow', downThreshold: 100, upThreshold: 155,
  },

  // ── LEGS ───────────────────────────────────────────────
  {
    id: 'squats', name: 'Squats', category: 'legs', icon: '🦵', level: 'Beginner',
    color: '#22c55e', gradient: 'linear-gradient(135deg,#22c55e,#10b981)',
    targetMuscles: 'Quads, Glutes, Hamstrings',
    description: 'Fundamental lower-body compound movement.',
    keyPoints: ['Chest up, back straight', 'Push knees over toes', 'Thighs parallel at bottom', 'Drive through heels'],
    angleType: 'knee', downThreshold: 105, upThreshold: 160,
  },
  {
    id: 'sumo-squats', name: 'Sumo Squats', category: 'legs', icon: '🏋️', level: 'Beginner',
    color: '#84cc16', gradient: 'linear-gradient(135deg,#84cc16,#22c55e)',
    targetMuscles: 'Inner Thighs, Glutes, Quads',
    description: 'Wide-stance squat emphasising inner thighs and glutes.',
    keyPoints: ['Feet wide, toes out 45°', 'Knees track toes', 'Deep squat', 'Keep back upright'],
    angleType: 'knee', downThreshold: 105, upThreshold: 160,
  },
  {
    id: 'lunges', name: 'Lunges', category: 'legs', icon: '🚶', level: 'Beginner',
    color: '#4ade80', gradient: 'linear-gradient(135deg,#4ade80,#22d3ee)',
    targetMuscles: 'Quads, Glutes, Hamstrings',
    description: 'Single-leg stepping exercise for balance and strength.',
    keyPoints: ['Step forward, knee at 90°', 'Back knee near floor', 'Front knee behind toe', 'Push back to start'],
    angleType: 'knee', downThreshold: 105, upThreshold: 160,
  },
  {
    id: 'jump-squats', name: 'Jump Squats', category: 'legs', icon: '🦘', level: 'Intermediate',
    color: '#f59e0b', gradient: 'linear-gradient(135deg,#f59e0b,#ef4444)',
    targetMuscles: 'Quads, Calves, Glutes',
    description: 'Explosive plyometric squat for power development.',
    keyPoints: ['Squat to parallel', 'Explode upward', 'Land softly, knees bent', 'Immediate re-squat'],
    angleType: 'knee', downThreshold: 105, upThreshold: 160,
  },
  {
    id: 'glute-bridge', name: 'Glute Bridge', category: 'legs', icon: '🌉', level: 'Beginner',
    color: '#a78bfa', gradient: 'linear-gradient(135deg,#a78bfa,#6366f1)',
    targetMuscles: 'Glutes, Hamstrings, Core',
    description: 'Lying hip thrust targeting posterior chain.',
    keyPoints: ['Feet flat on floor', 'Drive hips up high', 'Squeeze glutes at top', 'Lower controlled'],
    angleType: 'hip', downThreshold: 120, upThreshold: 160,
  },
  {
    id: 'calf-raises', name: 'Calf Raises', category: 'legs', icon: '👟', level: 'Beginner',
    color: '#34d399', gradient: 'linear-gradient(135deg,#34d399,#06b6d4)',
    targetMuscles: 'Calves (Gastrocnemius, Soleus)',
    description: 'Standing heel raise to strengthen calf muscles.',
    keyPoints: ['Stand tall', 'Rise on toes fully', 'Hold briefly at top', 'Lower slowly'],
    angleType: 'knee', downThreshold: 140, upThreshold: 170,
  },

  // ── BACK ───────────────────────────────────────────────
  {
    id: 'superman', name: 'Superman', category: 'back', icon: '🦸', level: 'Beginner',
    color: '#f97316', gradient: 'linear-gradient(135deg,#f97316,#fbbf24)',
    targetMuscles: 'Lower Back, Glutes, Rear Delts',
    description: 'Prone back extension strengthening the posterior chain.',
    keyPoints: ['Lie face down', 'Lift arms and legs together', 'Hold at top 2 seconds', 'Lower controlled'],
    angleType: 'hip', downThreshold: 150, upThreshold: 175,
  },
  {
    id: 'good-mornings', name: 'Good Mornings', category: 'back', icon: '☀️', level: 'Intermediate',
    color: '#fbbf24', gradient: 'linear-gradient(135deg,#fbbf24,#f97316)',
    targetMuscles: 'Hamstrings, Lower Back, Glutes',
    description: 'Hip-hinge movement for posterior chain strength.',
    keyPoints: ['Bar on upper back', 'Hinge at hips', 'Back stays flat', 'Drive hips forward to stand'],
    angleType: 'hip', downThreshold: 120, upThreshold: 165,
  },
  {
    id: 'bent-over-row', name: 'Bent Over Row', category: 'back', icon: '🏋️', level: 'Intermediate',
    color: '#fb923c', gradient: 'linear-gradient(135deg,#fb923c,#ef4444)',
    targetMuscles: 'Lats, Rhomboids, Biceps',
    description: 'Barbell or dumbbell row for upper back thickness.',
    keyPoints: ['Hinge forward 45°', 'Pull elbows to sides', 'Squeeze shoulder blades', 'Lower fully'],
    angleType: 'elbow', downThreshold: 100, upThreshold: 155,
  },
  {
    id: 'back-extension', name: 'Back Extension', category: 'back', icon: '🔙', level: 'Beginner',
    color: '#ef4444', gradient: 'linear-gradient(135deg,#ef4444,#a855f7)',
    targetMuscles: 'Erector Spinae, Glutes',
    description: 'Hyperextension movement for lower back endurance.',
    keyPoints: ['Hips on pad', 'Lower torso down', 'Raise to parallel', 'Do not hyperextend'],
    angleType: 'hip', downThreshold: 120, upThreshold: 165,
  },
  {
    id: 'bird-dog', name: 'Bird Dog', category: 'back', icon: '🐦', level: 'Beginner',
    color: '#22d3ee', gradient: 'linear-gradient(135deg,#22d3ee,#6366f1)',
    targetMuscles: 'Core, Lower Back, Glutes',
    description: 'Quadruped opposite arm-leg extension for stability.',
    keyPoints: ['Start on hands and knees', 'Extend opposite arm+leg', 'Hold 2 seconds', 'Return and switch'],
    angleType: 'hip', downThreshold: 150, upThreshold: 175,
  },

  // ── SHOULDERS ──────────────────────────────────────────
  {
    id: 'shoulder-press', name: 'Shoulder Press', category: 'shoulders', icon: '🏋️', level: 'Intermediate',
    color: '#3b82f6', gradient: 'linear-gradient(135deg,#3b82f6,#6366f1)',
    targetMuscles: 'Front & Side Deltoids, Triceps',
    description: 'Overhead pressing for shoulder mass and strength.',
    keyPoints: ['Elbows at 90° at start', 'Press directly overhead', 'Fully lock out', 'Lower to ear level'],
    angleType: 'elbow', downThreshold: 100, upThreshold: 155,
  },
  {
    id: 'lateral-raise', name: 'Lateral Raise', category: 'shoulders', icon: '🦅', level: 'Beginner',
    color: '#60a5fa', gradient: 'linear-gradient(135deg,#60a5fa,#22d3ee)',
    targetMuscles: 'Side Deltoids',
    description: 'Dumbbell raise to the side for shoulder width.',
    keyPoints: ['Slight bend in elbow', 'Raise to shoulder height', 'Pinky slightly higher', 'Lower slowly'],
    angleType: 'kneeRaise', downThreshold: 150, upThreshold: 90,
  },
  {
    id: 'front-raise', name: 'Front Raise', category: 'shoulders', icon: '⬆️', level: 'Beginner',
    color: '#38bdf8', gradient: 'linear-gradient(135deg,#38bdf8,#6366f1)',
    targetMuscles: 'Front Deltoids',
    description: 'Dumbbell raise to front for anterior deltoid.',
    keyPoints: ['Arms straight', 'Raise to shoulder height', 'Control the descent', 'Alternate or both'],
    angleType: 'kneeRaise', downThreshold: 150, upThreshold: 90,
  },
  {
    id: 'arnold-press', name: 'Arnold Press', category: 'shoulders', icon: '💪', level: 'Intermediate',
    color: '#818cf8', gradient: 'linear-gradient(135deg,#818cf8,#3b82f6)',
    targetMuscles: 'All 3 Deltoid Heads, Triceps',
    description: 'Rotating shoulder press invented by Arnold Schwarzenegger.',
    keyPoints: ['Start palms facing you', 'Rotate outward as you press', 'Full overhead extension', 'Reverse on the way down'],
    angleType: 'elbow', downThreshold: 100, upThreshold: 155,
  },
  {
    id: 'upright-row', name: 'Upright Row', category: 'shoulders', icon: '⬆️', level: 'Intermediate',
    color: '#a78bfa', gradient: 'linear-gradient(135deg,#a78bfa,#3b82f6)',
    targetMuscles: 'Traps, Side Deltoids',
    description: 'Vertical pull targeting traps and lateral deltoids.',
    keyPoints: ['Grip narrow, overhand', 'Pull to chin height', 'Elbows above wrists', 'Lower controlled'],
    angleType: 'elbow', downThreshold: 90, upThreshold: 150,
  },

  // ── ARMS ───────────────────────────────────────────────
  {
    id: 'bicep-curls', name: 'Bicep Curls', category: 'arms', icon: '💪', level: 'Beginner',
    color: '#a855f7', gradient: 'linear-gradient(135deg,#a855f7,#ec4899)',
    targetMuscles: 'Biceps Brachii',
    description: 'Classic isolation exercise for bicep size and strength.',
    keyPoints: ['Elbows stationary at sides', 'Full range of motion', 'Control the negative', 'Squeeze at top'],
    angleType: 'elbowCurl', downThreshold: 150, upThreshold: 60,
  },
  {
    id: 'hammer-curls', name: 'Hammer Curls', category: 'arms', icon: '🔨', level: 'Beginner',
    color: '#c026d3', gradient: 'linear-gradient(135deg,#c026d3,#7c3aed)',
    targetMuscles: 'Biceps, Brachialis, Forearms',
    description: 'Neutral-grip curl for overall arm thickness.',
    keyPoints: ['Thumbs up grip', 'Elbows fixed at sides', 'Curl to shoulder', 'Lower slowly'],
    angleType: 'elbowCurl', downThreshold: 150, upThreshold: 60,
  },
  {
    id: 'tricep-dips', name: 'Tricep Dips', category: 'arms', icon: '💺', level: 'Beginner',
    color: '#7c3aed', gradient: 'linear-gradient(135deg,#7c3aed,#4f46e5)',
    targetMuscles: 'Triceps, Chest, Shoulders',
    description: 'Bodyweight dip for tricep mass.',
    keyPoints: ['Hands on edge behind', 'Lower until elbows 90°', 'Press back up fully', 'Keep torso upright'],
    angleType: 'elbow', downThreshold: 100, upThreshold: 155,
  },
  {
    id: 'overhead-tricep', name: 'Overhead Tricep Ext.', category: 'arms', icon: '🔝', level: 'Intermediate',
    color: '#ec4899', gradient: 'linear-gradient(135deg,#ec4899,#f97316)',
    targetMuscles: 'Long Head Triceps',
    description: 'Overhead extension for full tricep stretch.',
    keyPoints: ['Upper arms vertical', 'Lower weight behind head', 'Full extension overhead', 'Elbows in'],
    angleType: 'elbowCurl', downThreshold: 90, upThreshold: 155,
  },
  {
    id: 'skull-crushers', name: 'Skull Crushers', category: 'arms', icon: '💀', level: 'Intermediate',
    color: '#f43f5e', gradient: 'linear-gradient(135deg,#f43f5e,#ec4899)',
    targetMuscles: 'Triceps (all 3 heads)',
    description: 'Lying tricep extension for maximum mass.',
    keyPoints: ['Lie flat on bench', 'Lower bar to forehead', 'Extend fully', 'Keep elbows fixed'],
    angleType: 'elbowCurl', downThreshold: 90, upThreshold: 155,
  },

  // ── CORE ───────────────────────────────────────────────
  {
    id: 'plank', name: 'Plank', category: 'core', icon: '🏔️', level: 'Beginner',
    color: '#f59e0b', gradient: 'linear-gradient(135deg,#f59e0b,#ef4444)',
    targetMuscles: 'Core, Shoulders, Glutes',
    description: 'Isometric core hold for stability and endurance.',
    keyPoints: ['Forearms on floor', 'Body perfectly straight', 'No hips sag or pike', 'Breathe steadily'],
    angleType: 'hip', downThreshold: 155, upThreshold: 180,
  },
  {
    id: 'crunches', name: 'Crunches', category: 'core', icon: '🔄', level: 'Beginner',
    color: '#fbbf24', gradient: 'linear-gradient(135deg,#fbbf24,#f97316)',
    targetMuscles: 'Rectus Abdominis',
    description: 'Classic abdominal crunch for core strength.',
    keyPoints: ['Feet flat on floor', 'Hands behind head lightly', 'Curl shoulders off floor', 'Lower with control'],
    angleType: 'trunk', downThreshold: 150, upThreshold: 110,
  },
  {
    id: 'leg-raises', name: 'Leg Raises', category: 'core', icon: '🦵', level: 'Intermediate',
    color: '#f97316', gradient: 'linear-gradient(135deg,#f97316,#fbbf24)',
    targetMuscles: 'Lower Abs, Hip Flexors',
    description: 'Lying leg raise for lower abdominal development.',
    keyPoints: ['Lie flat, back pressed down', 'Raise legs to 90°', 'Lower slowly without touching', 'Keep legs straight'],
    angleType: 'kneeRaise', downThreshold: 160, upThreshold: 80,
  },
  {
    id: 'mountain-climbers', name: 'Mountain Climbers', category: 'core', icon: '⛰️', level: 'Intermediate',
    color: '#ef4444', gradient: 'linear-gradient(135deg,#ef4444,#f59e0b)',
    targetMuscles: 'Core, Shoulders, Hip Flexors',
    description: 'Dynamic plank with alternating knee drives.',
    keyPoints: ['Start in push-up position', 'Drive knees to chest alternately', 'Keep hips level', 'Move fast'],
    angleType: 'kneeRaise', downThreshold: 140, upThreshold: 70,
  },
  {
    id: 'bicycle-crunches', name: 'Bicycle Crunches', category: 'core', icon: '🚴', level: 'Intermediate',
    color: '#0ea5e9', gradient: 'linear-gradient(135deg,#0ea5e9,#a855f7)',
    targetMuscles: 'Obliques, Rectus Abdominis',
    description: 'Rotating crunch with alternating knee drive for obliques.',
    keyPoints: ['Shoulders off floor', 'Rotate elbow to opposite knee', 'Fully extend other leg', 'Controlled rhythm'],
    angleType: 'trunk', downThreshold: 150, upThreshold: 110,
  },

  // ── CARDIO ─────────────────────────────────────────────
  {
    id: 'jumping-jacks', name: 'Jumping Jacks', category: 'cardio', icon: '⭐', level: 'Beginner',
    color: '#06b6d4', gradient: 'linear-gradient(135deg,#06b6d4,#3b82f6)',
    targetMuscles: 'Full Body, Cardio',
    description: 'Full-body cardio exercise improving coordination.',
    keyPoints: ['Jump feet wide simultaneously', 'Raise arms overhead', 'Return together', 'Maintain rhythm'],
    angleType: 'kneeRaise', downThreshold: 160, upThreshold: 80,
  },
  {
    id: 'high-knees', name: 'High Knees', category: 'cardio', icon: '🏃', level: 'Beginner',
    color: '#22d3ee', gradient: 'linear-gradient(135deg,#22d3ee,#4ade80)',
    targetMuscles: 'Hip Flexors, Core, Cardio',
    description: 'Running in place with exaggerated knee drive.',
    keyPoints: ['Drive knees above hip height', 'Pump arms in rhythm', 'Stay on balls of feet', 'Maintain pace'],
    angleType: 'kneeRaise', downThreshold: 140, upThreshold: 70,
  },
  {
    id: 'burpees', name: 'Burpees', category: 'cardio', icon: '💥', level: 'Advanced',
    color: '#f97316', gradient: 'linear-gradient(135deg,#f97316,#ef4444)',
    targetMuscles: 'Full Body, Cardio, Strength',
    description: 'Full-body explosive movement for conditioning.',
    keyPoints: ['Drop to push-up position', 'Perform push-up', 'Jump feet to hands', 'Jump and clap overhead'],
    angleType: 'knee', downThreshold: 105, upThreshold: 160,
  },
  {
    id: 'jump-rope', name: 'Jump Rope', category: 'cardio', icon: '🪢', level: 'Beginner',
    color: '#a78bfa', gradient: 'linear-gradient(135deg,#a78bfa,#06b6d4)',
    targetMuscles: 'Calves, Coordination, Cardio',
    description: 'Simulated jump rope for cardio and footwork.',
    keyPoints: ['Stay on toes', 'Small jumps, consistent rhythm', 'Wrists rotate rope', 'Land softly'],
    angleType: 'knee', downThreshold: 150, upThreshold: 170,
  },
  {
    id: 'box-jumps', name: 'Box Jumps', category: 'cardio', icon: '📦', level: 'Intermediate',
    color: '#fbbf24', gradient: 'linear-gradient(135deg,#fbbf24,#f97316)',
    targetMuscles: 'Quads, Glutes, Explosive Power',
    description: 'Plyometric jump onto elevated surface for power.',
    keyPoints: ['Load with squat', 'Explode up with arms', 'Land softly, knees bent', 'Step down safely'],
    angleType: 'knee', downThreshold: 105, upThreshold: 160,
  },
];
